name: Archive Build Artifact
on:
  push:
    branches: [ "main" ]
jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Creates a folder
        run: mkdir downloads
        
      - name: Add artifacts to publish
        run: |
          cd downloads
          echo `alpha` > alpha.html
          echo `bravo` > bravo.html
          echo `charlie` > charlie.html
          cd..

      - name: Upload action
        uses: actions/upload-artifact@v4
        with:
          name: assets-for-download
          path: downloads